// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscGbtrwOJZTAmcCTg0iRMpG3z-ljaAKk',
    appId: '1:888161417902:web:50d5fa191d1234da2f8b3f',
    messagingSenderId: '888161417902',
    projectId: 'sunnyapp00',
    authDomain: 'sunnyapp00.firebaseapp.com',
    storageBucket: 'sunnyapp00.firebasestorage.app',
    measurementId: 'G-DF5SKND34W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbLmNCnYScA1S0oKVnMrY7vpFLxTLh3ys',
    appId: '1:888161417902:android:778e236282dd9f5d2f8b3f',
    messagingSenderId: '888161417902',
    projectId: 'sunnyapp00',
    storageBucket: 'sunnyapp00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbdPOa6K9dDa5vCt2s6nydvG9HUyrhoH0',
    appId: '1:888161417902:ios:3be11a336bc6baca2f8b3f',
    messagingSenderId: '888161417902',
    projectId: 'sunnyapp00',
    storageBucket: 'sunnyapp00.firebasestorage.app',
    iosBundleId: 'io.law.sunny',
  );
}
